sensor:
  id: "humidity_sensor1"
  type: "humidity"
  distribution: "beta"
  unit: "%"
  min_value: 15
  max_value: 26
  mean: 22
  alpha: 1
  beta: 4
  std_dev: 2.3
  interval_ms: 500

anomaly:
  generate: true
  margin: 10
  prob: 0.03

pattern:
  generate: true
  interval: "hour"
  amplitude: 5
  repeat: 24

kafka:
  brokers: "kafka.default.svc.cluster.local:9092"
  topic: "humidity-data"
