apiVersion: v1
kind: ConfigMap
metadata:
    name: soil-moisture-config-file
data:
    config.yaml: |
        sensor:
            id: "soil_sensor1"
            type: "soil-moisture"
            distribution: "beta"
            unit: "%"
            min_value: 15
            max_value: 26
            mean: 22
            alpha: 2
            beta: 3
            std_dev: 2.3
            interval_ms: 10000

        anomaly:
            generate: true
            margin: 10
            prob: 0.03

        pattern:
            generate: false
            interval: "minute"
            amplitude: 3.6
            repeat: 60

        kafka:
            brokers: "kafka.default.svc.cluster.local:9092"
            topic: "soil-data"

